### ISSUE TITLE
Laser_mapping and laser_loc are broken

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsAcademy#2008]
**Laser_mapping** and **laser_loc** are broken:
```
[ERROR] [1681486219.098906868]: [STDR_PARSER] Failed to load file '/catkin_ws/src/stdr_simulator/stdr_resources/resources/robots/amigobot.xml'
Error was 'Failed to open file'
If error was 'Error reading end tag' you have a malformed xml file
[robot_spawn_664947ce1ef7_110_3002388729644700876-5] process has died [pid 212, exit code 255, cmd /catkin_ws/devel/lib/stdr_robot/robot_handler add /catkin_ws/src/stdr_simulator/stdr_resources/resources/robots/amigobot.xml 4 8 0 __name:=robot_spawn_664947ce1ef7_110_3002388729644700876 __log:=/root/.ros/log/430e9e8a-dad9-11ed-a20e-0242ac110002/robot_spawn_664947ce1ef7_110_3002388729644700876-5.log].
log file: /root/.ros/log/430e9e8a-dad9-11ed-a20e-0242ac110002/robot_spawn_664947ce1ef7_110_3002388729644700876-5*.log
```

Also at **laser_loc**:
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/RoboticsAcademy/exercises/static/exercises/laser_loc/web-template/gui.py", line 184, in run
    self.gui.update()
  File "/RoboticsAcademy/exercises/static/exercises/laser_loc/web-template/gui.py", line 78, in update
    self.payload["pos_vertices"], self.payload["sonar_sensor"] = self.map.setSonarValues()
  File "/RoboticsAcademy/exercises/static/exercises/laser_loc/web-template/map.py", line 198, in setSonarValues
    hipotenusa = distance/(math.cos(cone/2))
TypeError: unsupported operand type(s) for /: 'list' and 'float'
```

_Originally posted by @pariaspe in https://github.com/JdeRobot/RoboticsAcademy/issues/1984#issuecomment-1508805066_

**Comment by Bhardwaj-Himanshu** [comment]
Hi @pariaspe,

Successfully reproduced the issue,here- 
![image](https://user-images.githubusercontent.com/74407676/235410702-88898b65-6ce1-4593-97ad-ed2a9db97f63.png)


Could you elaborate on how one can start working on this issue?

**After looking at the issue I think**
This has something to do with `catkin_dependencies` or `catkin_config_file`.

Let me know about your thoughts on this and if you are working on anything?
Thanks

**Comment by pariaspe** [comment]
Hey @Bhardwaj-Himanshu ,

I'm not working on it right now, I ain't time. But I have an idea on what it might be happening.

There are al least two different issues:
1. `amigobot.xml` malformed. Take a look at the file, it may have a unclosed tag or the some XML specification may be missing.
2. On `map.py` there is a python mistake where a list is divided by a float which is not supported.

**Comment by Bhardwaj-Himanshu** [comment]
Thanks for the feedback @pariaspe,

On taking a look at `map.py`
It has these many division processes going on-
```py
#these were int values but I am unsure about self.RTz command
RTz = self.RTz(pi/2, 50, 70, 0)
base = radius/2
alfa = math.asin((base)/radius)
hipotenusa = distance/(math.cos(cone/2))

# I suspect it is from division below this comment
orientation = self.sonares[i][2] - cone/2
orientation = self.sonares[i][2] + cone/2
orientation = self.sonares[i][2] + cone/2
orientation = self.sonares[i][2] - cone/2
```

On taking a look at amigobot.xml, which I could not find the file but found, `amigobot_without_gui.launch`, `amigobot_launch`
`The syntax of both feels good to me as code editor didn't raise any red underlines as well`
So it is most probably some XML specification missing!

**Comment by pariaspe** [comment]
The traceback tells you where the error is happening:
```python
hipotenusa = distance/(math.cos(cone/2))
```

> On taking a look at `amigobot.xml`, which I could not find the file but found, `amigobot_without_gui.launch`, `amigobot_launch` `The syntax of both feels good to me as code editor didn't raise any red underlines as well` So it is most probably some XML specification missing!

Those files are cloned from [here](https://github.com/stdr-simulator-ros-pkg/stdr_simulator). I've just realized that `amigobot.xml` file is missing (check it on the repo), raising the error *"Failed to open file"*. Could you try to launch the exercise without line 12 in 
`amigobot_without_gui.launch`?

**Comment by Bhardwaj-Himanshu** [comment]
Thanks for all the clues @pariaspe,

After your suggestions, I commented out the 
```xml
<!-- <node name="$(anon robot_spawn)" pkg="stdr_robot" type="robot_handler" args="add $(find stdr_resources)/resources/robots/amigobot.xml 4 8 0"/>-->
```
from both the files `amigobot_without_gui.launch` and `amigobot_launch`, I know you said about just one, but just testing in the moment.

I then build both the BASE and RADI images of the docker container and named it as `test`.
Now before I run the docker container using-
```docker
docker run --rm -it -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/test_image_id
```

I try to install the `requirements.txt` using `pip install -r requirements.txt`
which always ends on the error below as-
```zsh
ERROR: Could not find a version that satisfies the requirement catkin-pkg-modules==0.5.2 (from versions: 66.0.0, 66.0.2)
ERROR: No matching distribution found for catkin-pkg-modules==0.5.2
```
Which denotes--> I have version 66.0.2 installed on system but I need 0.5.2--> so when I manually tweak the requirements.txt file catkin-pkg-modules==0.5.2 it again ends on error.

Could you tell the possible reason why?

**Comment by pariaspe** [comment]
Hey @Bhardwaj-Himanshu ,
Everything went well while running?
You don't need to install `requirements.txt` it is done while building the RADI.

**Comment by Bhardwaj-Himanshu** [comment]
Hmm, I think I am stuck on installing `django` or other `bootstrap` dependencies or libraries.

Here is the output of django version checker command-
```zsh
python -m django --version
4.2.1
```
and here is a log I am running into when I run `docker run -p 8000:8000 test_image_id`
```zsh
 in <dictcomp>
    return {
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'rest_framework.templatetags.rest_framework': cannot import name 'parse_header' from 'django.http.multipartparser' (/usr/local/lib/python3.8/dist-packages/django/http/multipartparser.py)
```

What I could identify that the system is missing, `django, bootstrap and rest frameworks` respectively, but there is django installed on the system!
Could be an error on the machine side as well, but I use this cloud VM instance for every docker image build, as I am bottlenecked by memory on my local machine.

I have tried running jderobot/roboticsacademy:latest a few days back and it worked fine!
Let me know your thoughts on this!

**Comment by pariaspe** [comment]
Hi, it seems that your BASE was not well generated. That dependency missing is installed [here](https://github.com/JdeRobot/RoboticsInfraestructure/blob/2d358c470804ab6ad0063356add17bc819da48a1/scripts/Dockerfile.base#L270). So, make sure that your dockerfile have that line.

**Comment by Bhardwaj-Himanshu** [comment]
Hi, I am attaching a screenshot of what did `dockerfile.base` look like before-

![image](https://user-images.githubusercontent.com/74407676/236260709-d1b93890-3b0a-47d7-a14a-4e36d30a8c23.png)

So the line was already added, but I'll try making the base image again tommorow most probably, power cut issues;(

**Comment by pariaspe** [comment]
Yes, that line is the one I am referring to. Ok, no problem, no need to hurry :+1:

**Comment by pariaspe** [comment]
Yes, we are restructuring a bit the repositories before gsoc23 kicks off. You can find the Dockerfiles [here](https://github.com/JdeRobot/RoboticsInfraestructure/tree/noetic-devel/scripts). You can build the RADI like always.

**Comment by Bhardwaj-Himanshu** [comment]
Ok pariaspe, we have a good news..........................that "exercise is still broken"->sorry for the PJ here!

I commented out the line 12 as mentioned by you from both the files `amigobot.launch` and `amigobot_without_gui`-
![image](https://user-images.githubusercontent.com/74407676/236675641-d79b06ba-689e-4064-9a17-865d82ec7634.png)
and the error output for both laser_loc and laser mapping looks like this-
![image](https://user-images.githubusercontent.com/74407676/236675659-ea0aef99-a0c9-4961-bf31-fa63410892df.png)

The BASE and RADI image build were both successful, and I do have one more doubt, `do we have to commit changes before making the Images, just saving the file should be okay right?`

Let me know what do you think about this-

Also to the GSOC point, my portfolio was rejected so if you could provide me the selected proposals or the profile of people who are selected that would be very helpful for me!

Also, keeping the `gsoc tag aside`, If I could contribute to the "contaniersing of visual circuit in any way" as I am interested in devops stuff, how things break and work! I know this won't be allowed as this could hinder the progress meter of the candidate,but looking as an open source organisation if I could would matter a lot to me!
Thanks

**Comment by Bhardwaj-Himanshu** [comment]
Ah, I'll give it a shot after commiting the changes as well then, but do I need to clone it again?
Cause Saving the changes first + then commiting them should work right?

Also, I'll keep an eye out for twitter too then, thanks👍

**Comment by pariaspe** [comment]
Are you talking about git commit or docker commit? You can do both, but I was talking about git commit the changes, push them on your forked repo and clone it inside the RADI while building the Dockerfile.

**Comment by Bhardwaj-Himanshu** [comment]
Yep I am talking about the git commit exactly, so I should first commit, push and then try to build the RADI image.
Gotcha!

**Comment by Bhardwaj-Himanshu** [comment]
Ah, I think it's been a long time! Pardon me had a lot going on my side, but active back again!--just moving homes and exams!

I am now making the RADI/BASE image for this issue, and will update you by evening!
Thanks @pariaspe

**Comment by pariaspe** [comment]
Hey @Bhardwaj-Himanshu , things have changed a lot in these last two weeks. We split the repository, so Dockerfiles are now also split. Take a look at this guide to build new [RADI](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/generate_a_mini_radi.md).

**Comment by Bhardwaj-Himanshu** [comment]
➜  scripts git:(#2008) sudo ./build.sh "#2008" noetic-devel main noetic test

Running this for a branch name gives me a "invalid use of -t flag error!"

**Comment by pawanw17** [comment]
Hi @Bhardwaj-Himanshu the script and its usage has been updated, use the latest master, and this should help:

https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/generate_a_mini_radi.md#usage

**Comment by AADI-234** [comment]
hello
Is this issue resolved or not
I'm new to github i want to contribute by solving issues related to DL, computer vision task and python.
Can someone help me out in this

**Comment by pariaspe** [comment]
Hi @AADI-234 ,
First step will be testing if the exercise has still the issue or not. Try to download latest RADI (or build a local [miniRADI](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/generate_a_mini_radi.md)) and running the exercise.

**Comment by jmplaza** [comment]
Hi @AADI-234, 

this issue is still open. Those exercises are broken. They are not related to DL neither Computer Vision. They are based on STDR simulator, not in Gazebo. Have you checked their user documentation? ([laser Mapping](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/laser_mapping), [laser_loc](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/laser_loc/))

In order to effectively contribute to RoboticsAcademy, first start using it :-) For instance the exercises FollowLine, ObstacleAvoidance, VacuumCleaner... And study the source code, feel free to ask here (or in [Discussions](https://github.com/JdeRobot/RoboticsAcademy/discussions)) any arising question!. Then you will become familiar with its software base and you will be closer to create your own Pull Request solving the issues.

You will find more context in [this paper](https://doi.org/10.1007/s11042-023-17514-z).

Cheers,

**Comment by damodardatta** [comment]
Hi,
i'm not able to find [laser Mapping](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/laser_mapping), [laser_loc](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/laser_loc/) in the latest RADI image list of exercises. Do i need to look for someother RADI image? or am i going wrong somewhere?

**Comment by pariaspe** [comment]
They might have been hidden since they were not working. You can make them available again by creating new entries to the database. Take a look at this [guide](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/InstructionsForDevelopers.md#How-to-add-a-new-exercise).

**Comment by jmplaza** [comment]
Yes, they are deprecated. They both are based in the [STDR Simulator](https://stdr-simulator-ros-pkg.github.io/)  and are now quite outdated with the latest frontend, REACT based. They require a major refactoring to be updated. Some information about them is available [here](https://gsyc.urjc.es/jmplaza/students/tfm-academy-vladislav_kravchenko-2022.pdf) (in Spanish, sorry).

**Comment by harsh839** [comment]
firstly amigobot.xml file doesn't exist in the repository so you can't call it

**Comment by javizqh** [comment]
The exercises have been redone and are available and working in the latest version
