### ISSUE TITLE
Ports still in use causing vnc visor to not work

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#2576]
During development, In case of refreshing the exercise page, I was getting this error persistently.

**RADI Version: 4.5.9, 4.5.13**

```
developer-container  | Xserver on :1 is running!
developer-container  | 16:36:05 [MainThread  ] [ERROR] (my_app_logger)  Port 5901 on localhost didn't become available within 20 seconds.
developer-container  | Traceback (most recent call last):
developer-container  |   File "//RoboticsAcademy/src/manager/manager/manager.py", line 470, in start
developer-container  |     self.process_messsage(message)
developer-container  |   File "//RoboticsAcademy/src/manager/manager/manager.py", line 371, in process_messsage
developer-container  |     self.trigger(message.command, data=message.data or None)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 922, in _get_trigger
developer-container  |     return event.trigger(model, *args, **kwargs)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 402, in trigger
developer-container  |     return self.machine._process(func)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 1211, in _process
developer-container  |     return trigger()
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 416, in _trigger
developer-container  |     self._process(event_data)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 439, in _process
developer-container  |     if trans.execute(event_data):
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 273, in execute
developer-container  |     event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 1146, in callbacks
developer-container  |     self.callback(func, event_data)
developer-container  |   File "/usr/local/lib/python3.10/dist-packages/transitions/core.py", line 1165, in callback
developer-container  |     func(event_data)
developer-container  |   File "//RoboticsAcademy/src/manager/manager/manager.py", line 221, in on_prepare_visualization
developer-container  |     self.visualization_launcher.run()
developer-container  |   File "/RoboticsAcademy/src/manager/manager/launcher/launcher_visualization.py", line 110, in run
developer-container  |     launcher = self.launch_module(module)
developer-container  |   File "/RoboticsAcademy/src/manager/manager/launcher/launcher_visualization.py", line 132, in launch_module
developer-container  |     launcher.run(process_terminated)
developer-container  |   File "/RoboticsAcademy/src/manager/manager/launcher/launcher_console.py", line 29, in run
developer-container  |     self.console_vnc.start_vnc(
developer-container  |   File "/RoboticsAcademy/src/manager/manager/vnc/vnc_server.py", line 39, in start_vnc
developer-container  |     self.wait_for_port("localhost", internal_port)
developer-container  |   File "/RoboticsAcademy/src/manager/manager/vnc/vnc_server.py", line 71, in wait_for_port
developer-container  |     raise TimeoutError(
developer-container  | TimeoutError: Port 5901 on localhost didn't become available within 20 seconds.

```

**Comment by pawanw17** [comment]
@Apoorvgarg-creator, You can try increasing the timeout here https://github.com/JdeRobot/RoboticsApplicationManager/blob/c6db1c609987f7b4ebb965477fa3fe18c91f8e42/manager/manager/vnc/vnc_server.py#L66

but other than that I won't be able to help much since I can not reproduce this...

**Comment by Apoorvgarg-creator** [comment]
Can you tell me where to update this ?

**Comment by pawanw17** [comment]
@Apoorvgarg-creator Click on the link there's a timeout parameter

**Comment by Apoorvgarg-creator** [comment]
Oh, Got it !

**Comment by javizqh** [comment]
Can this be closed @Apoorvgarg-creator ?

**Comment by Apoorvgarg-creator** [comment]
> Can this be closed @Apoorvgarg-creator ?

Yes

**Comment by pawanw17** [comment]
@Apoorvgarg-creator what worked?

**Comment by dduro2020** [comment]
I have tried increasing the timeout to 60 seconds, but the error persists, what did you do? @Apoorvgarg-creator

**Comment by Apoorvgarg-creator** [comment]
The current manual fix -

Inside the _Robotics Academy Docker Image (Container)_ -

1. **Check if the port is still in use or not** - ```lsof -i :5901``` if this returns output, it means in use.
2. **Kill the process on the port before reloading or changing into new exercise** - [How to kill a process running on particular port in Linux?](https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux)

In case the ```lsof -i :5901``` is not working, look at the below stackoverflow link -
[how to make sure that a certain port is not occupied by any other process](https://stackoverflow.com/questions/8817500/how-to-make-sure-that-a-certain-port-is-not-occupied-by-any-other-process#:~:text=You%20can%20use%20%22netstat%22%20to,process%20id%20of%20that%20process)

**Comment by Apoorvgarg-creator** [comment]
We are looking for the proper fix for this issue. Hence, reopened.

**Comment by javizqh** [comment]
With the RoboticsBackend 4.6.5 this now longer happens. If it happens again we will reopen it
