### ISSUE TITLE
PX4 Error while setting up Drone Gymkhana

### ISSUE THREAD

**Issue by joeljosephjin** [JdeRobot/RoboticsAcademy#556]
Command:
```
$ roslaunch drone_gymkhana.launch
```

Specific Error:
```
ERROR: cannot launch node of type [px4/px4]: Cannot locate node of type [px4] in package [px4]. Make sure file exists in package path and permission is set to executable (chmod +x)
```

Whole Output:
```
... logging to /home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/roslaunch-elian-ThinkPad-L440-23850.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://elian-ThinkPad-L440:44675/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mission/use_mission_item_int: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: odom
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: odom
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: odom
 * /mavros/wheel_odometry/tf/send: False
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: melodic
 * /rosversion: 1.14.5
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    my_solution (drone_wrapper/play_python_code)
    rqt_gui (rqt_gui/rqt_gui)
    sitl (px4/px4)
    vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541 (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://localhost:11311

ERROR: cannot launch node of type [px4/px4]: Cannot locate node of type [px4] in package [px4]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[gazebo-2]: started with pid [23866]
process[gazebo_gui-3]: started with pid [23869]
process[vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541-4]: started with pid [23874]
process[mavros-5]: started with pid [23877]
process[rqt_gui-6]: started with pid [23878]
process[my_solution-7]: started with pid [23879]
[ WARN] [1593070135.621686898, 484.320000000]: Shutdown request received.
[ WARN] [1593070135.621846737, 484.320000000]: Reason given for shutdown: [new node registered with same name]
Option --perspective-file must reference existing file
[rqt_gui-6] process has died [pid 23878, exit code 1, cmd /opt/ros/melodic/lib/rqt_gui/rqt_gui --perspective-file /opt/ros/melodic/share/jderobot_assets/perspectives/drone_teleop_vel.perspective __name:=rqt_gui __log:=/home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/rqt_gui-6.log].
log file: /home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/rqt_gui-6*.log
[ INFO] [1593070143.973207359, 492.372000000]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1593070143.975388687, 492.372000000]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1593070143.975550874, 492.372000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1593070143.975724963, 492.372000000]: GCS bridge disabled
[ INFO] [1593070144.953933797, 493.352000000]: Plugin 3dr_radio loaded
[ INFO] [1593070144.957892869, 493.356000000]: Plugin 3dr_radio initialized
[ INFO] [1593070144.958032612, 493.356000000]: Plugin actuator_control loaded
[ INFO] [1593070144.962182279, 493.360000000]: Plugin actuator_control initialized
[ INFO] [1593070145.646871099, 494.044000000]: Plugin adsb loaded
[ INFO] [1593070145.649946793, 494.048000000]: Plugin adsb initialized
[ INFO] [1593070145.650092014, 494.048000000]: Plugin altitude loaded
[ INFO] [1593070145.651237671, 494.048000000]: Plugin altitude initialized
[ INFO] [1593070145.651340950, 494.048000000]: Plugin cam_imu_sync loaded
[ INFO] [1593070145.651969840, 494.048000000]: Plugin cam_imu_sync initialized
[ INFO] [1593070145.652089429, 494.048000000]: Plugin command loaded
[ INFO] [1593070145.656833451, 494.052000000]: Plugin command initialized
[ INFO] [1593070145.656978905, 494.052000000]: Plugin companion_process_status loaded
[ INFO] [1593070145.659565610, 494.056000000]: Plugin companion_process_status initialized
[ INFO] [1593070145.659697096, 494.056000000]: Plugin debug_value loaded
[ INFO] [1593070145.663043750, 494.060000000]: Plugin debug_value initialized
[ INFO] [1593070145.663088493, 494.060000000]: Plugin distance_sensor blacklisted
[ INFO] [1593070145.663236353, 494.060000000]: Plugin fake_gps loaded
[ INFO] [1593070145.673137879, 494.072000000]: Plugin fake_gps initialized
[ INFO] [1593070145.673359452, 494.072000000]: Plugin ftp loaded
[ INFO] [1593070145.678605867, 494.076000000]: Plugin ftp initialized
[ INFO] [1593070145.678755188, 494.076000000]: Plugin global_position loaded
[ INFO] [1593070145.690649266, 494.088000000]: Plugin global_position initialized
[ INFO] [1593070145.690806782, 494.088000000]: Plugin gps_rtk loaded
[ INFO] [1593070145.692527305, 494.088000000]: Plugin gps_rtk initialized
[ INFO] [1593070145.692679306, 494.088000000]: Plugin hil loaded
[ INFO] [1593070145.703475616, 494.100000000]: Plugin hil initialized
[ INFO] [1593070145.703639694, 494.100000000]: Plugin home_position loaded
[ INFO] [1593070145.706307819, 494.104000000]: Plugin home_position initialized
[ INFO] [1593070145.706446838, 494.104000000]: Plugin imu loaded
[ INFO] [1593070145.711838393, 494.108000000]: Plugin imu initialized
[ INFO] [1593070145.711951135, 494.108000000]: Plugin landing_target loaded
[ INFO] [1593070145.723492101, 494.120000000]: Plugin landing_target initialized
[ INFO] [1593070145.723656592, 494.120000000]: Plugin local_position loaded
[ INFO] [1593070145.729833833, 494.128000000]: Plugin local_position initialized
[ INFO] [1593070145.729982023, 494.128000000]: Plugin log_transfer loaded
[ INFO] [1593070145.732387109, 494.128000000]: Plugin log_transfer initialized
[ INFO] [1593070145.732519418, 494.128000000]: Plugin manual_control loaded
[ INFO] [1593070145.735282709, 494.132000000]: Plugin manual_control initialized
[ INFO] [1593070145.735436525, 494.132000000]: Plugin mocap_pose_estimate loaded
[ INFO] [1593070145.738651423, 494.136000000]: Plugin mocap_pose_estimate initialized
[ INFO] [1593070145.738784320, 494.136000000]: Plugin mount_control loaded
[ INFO] [1593070145.742312536, 494.140000000]: Plugin mount_control initialized
[ INFO] [1593070145.742450223, 494.140000000]: Plugin obstacle_distance loaded
[ INFO] [1593070145.744531066, 494.140000000]: Plugin obstacle_distance initialized
[ INFO] [1593070145.744667603, 494.140000000]: Plugin odom loaded
[ INFO] [1593070145.748530214, 494.144000000]: Plugin odom initialized
[ INFO] [1593070145.748667591, 494.144000000]: Plugin onboard_computer_status loaded
[ INFO] [1593070145.750704359, 494.148000000]: Plugin onboard_computer_status initialized
[ INFO] [1593070145.750829760, 494.148000000]: Plugin param loaded
[ INFO] [1593070145.753697432, 494.152000000]: Plugin param initialized
[ INFO] [1593070145.754014757, 494.152000000]: Plugin px4flow loaded
[ INFO] [1593070145.764244441, 494.160000000]: Plugin px4flow initialized
[ INFO] [1593070145.764457594, 494.160000000]: Plugin rangefinder blacklisted
[ INFO] [1593070145.765689243, 494.164000000]: Plugin rc_io loaded
[ INFO] [1593070145.772873667, 494.168000000]: Plugin rc_io initialized
[ INFO] [1593070145.772944264, 494.172000000]: Plugin safety_area blacklisted
[ INFO] [1593070145.773076799, 494.172000000]: Plugin setpoint_accel loaded
[ INFO] [1593070145.775503915, 494.172000000]: Plugin setpoint_accel initialized
[ INFO] [1593070145.775680404, 494.172000000]: Plugin setpoint_attitude loaded
[ INFO] [1593070146.049424883, 494.444000000]: Plugin setpoint_attitude initialized
[ INFO] [1593070146.049769796, 494.444000000]: Plugin setpoint_position loaded
[ INFO] [1593070146.064601984, 494.460000000]: Plugin setpoint_position initialized
[ INFO] [1593070146.064787428, 494.460000000]: Plugin setpoint_raw loaded
[ INFO] [1593070146.072188053, 494.468000000]: Plugin setpoint_raw initialized
[ INFO] [1593070146.072502146, 494.468000000]: Plugin setpoint_trajectory loaded
[ INFO] [1593070146.077407134, 494.476000000]: Plugin setpoint_trajectory initialized
[ INFO] [1593070146.077582455, 494.476000000]: Plugin setpoint_velocity loaded
[ INFO] [1593070146.082686564, 494.480000000]: Plugin setpoint_velocity initialized
[ INFO] [1593070146.082895846, 494.480000000]: Plugin sys_status loaded
[ INFO] [1593070146.092707377, 494.488000000]: Plugin sys_status initialized
[ INFO] [1593070146.092873645, 494.488000000]: Plugin sys_time loaded
[ INFO] [1593070146.098299926, 494.496000000]: TM: Timesync mode: MAVLINK
[ INFO] [1593070146.099417426, 494.496000000]: Plugin sys_time initialized
[ INFO] [1593070146.099541023, 494.496000000]: Plugin trajectory loaded
[ INFO] [1593070146.104653655, 494.500000000]: Plugin trajectory initialized
[ INFO] [1593070146.104816989, 494.500000000]: Plugin vfr_hud loaded
[ INFO] [1593070146.105568740, 494.504000000]: Plugin vfr_hud initialized
[ INFO] [1593070146.105630433, 494.504000000]: Plugin vibration blacklisted
[ INFO] [1593070146.105786871, 494.504000000]: Plugin vision_pose_estimate loaded
[ INFO] [1593070146.112391638, 494.508000000]: Plugin vision_pose_estimate initialized
[ INFO] [1593070146.112555607, 494.508000000]: Plugin vision_speed_estimate loaded
[ INFO] [1593070146.115578184, 494.512000000]: Plugin vision_speed_estimate initialized
[ INFO] [1593070146.115725308, 494.512000000]: Plugin waypoint loaded
[ INFO] [1593070146.120012288, 494.516000000]: Plugin waypoint initialized
[ INFO] [1593070146.120069184, 494.516000000]: Plugin wheel_odometry blacklisted
[ INFO] [1593070146.120183592, 494.516000000]: Plugin wind_estimation loaded
[ INFO] [1593070146.120738575, 494.516000000]: Plugin wind_estimation initialized
[ INFO] [1593070146.120788166, 494.516000000]: Autostarting mavlink via USB on PX4
[ INFO] [1593070146.120852335, 494.516000000]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1593070146.120896430, 494.516000000]: Built-in MAVLink package version: 2020.6.6
[ INFO] [1593070146.120948055, 494.516000000]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1593070146.120994869, 494.516000000]: MAVROS started. MY ID 1.240, TARGET ID 1.1
Traceback (most recent call last):
  File "/home/elian/Documents/drone_gymkhana/my_solution.py", line 8, in <module>
    from drone_wrapper import DroneWrapper
  File "/opt/ros/melodic/lib/python2.7/dist-packages/drone_wrapper/__init__.py", line 1, in <module>
    from drone_wrapper_class import DroneWrapper
ModuleNotFoundError: No module named 'drone_wrapper_class'
[my_solution-7] process has died [pid 23879, exit code 1, cmd /opt/ros/melodic/lib/drone_wrapper/play_python_code /home/elian/Documents/drone_gymkhana/my_solution.py __name:=my_solution __log:=/home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/my_solution-7.log].
log file: /home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/my_solution-7*.log
[INFO] [1593070151.211301, 0.000000]: Loading model XML from file /opt/ros/melodic/share/jderobot_assets/models/iris_dual_cam/iris_dual_cam.sdf
[INFO] [1593070151.254365, 499.564000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1593070151.257004, 499.568000]: Calling service /gazebo/spawn_sdf_model
[ERROR] [1593070151.403532138, 499.716000000]: SpawnModel: Failure - model name iris already exist.
[INFO] [1593070151.447905, 499.732000]: Spawn status: SpawnModel: Failure - entity already exists.
[ERROR] [1593070151.450624, 499.732000]: Spawn service failed. Exiting.
[vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541-4] process has died [pid 23874, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -sdf -file /opt/ros/melodic/share/jderobot_assets/models/iris_dual_cam/iris_dual_cam.sdf -model iris -x 0 -y 0 -z 1 -R 0 -P 0 -Y 0 __name:=vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541 __log:=/home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541-4.log].
log file: /home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/vehicle_spawn_elian_ThinkPad_L440_23850_2455365306996860541-4*.log
[ INFO] [1593070154.595575629]: Finished loading Gazebo ROS API Plugin.
[ WARN] [1593070154.597550140, 502.572000000]: Shutdown request received.
[ WARN] [1593070154.597828063, 502.572000000]: Reason given for shutdown: [new node registered with same name]
[ INFO] [1593070154.616133833]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[gazebo-2] process has died [pid 23866, exit code 255, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/elian/Documents/drone_gymkhana/drone_gymkhana.world __name:=gazebo __log:=/home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/gazebo-2.log].
log file: /home/elian/.ros/log/55013450-b6b4-11ea-8e42-e8b1fc0f6757/gazebo-2*.log
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
```

**Comment by pariaspe** [comment]
Hi @joeljosephjin,

We made some changes that will be available in the next ROS sync (in 10d more o less). However, if you want to try it right now you can clone [Assets](https://github.com/JdeRobot/assets) and [Drones](https://github.com/JdeRobot/drones) repositories into your catkin_ws/src and rebuild it.

**Comment by diegomrt** [comment]
Hi @joeljosephjin 

In addition, it seems that you have some troubles with the PX4 (Firmware) package. MavROS is launching OK in your system but the PX4 SITL fails. Did you get any errors when compiling your catkin_ws?

To check it, try to run `roslaunch px4 posix_sitl.launch` and let us know if it works.

**Comment by pariaspe** [comment]
ROS didn't find PX4 package, might have some troubles with `ROS_PACKAGE_PATH` envvar. Try `roslaunch px4 mavros_posix_sitl.launch` to confirm.

Stale issue. Closing.
